### ISSUE TITLE
Test is failing 

### ISSUE THREAD

**Issue by vanerleo** [olegabu/cognito-helper#2]
Cannot create a user, keep on getting : 

  Uncaught AssertionError: 'UnrecognizedClientException' == 409
      at test/cognito-helper.js:20:16

here is the output:
 CognitoHelper.
[2016-01-23 16:13:32.325] [DEBUG] CognitoHelper - lookupDeveloperIdentity { IdentityPoolId: 'ap-northeast-1:84e40d07-e851-**************_1',
  DeveloperUserIdentifier: 'user@test.com',
  MaxResults: 10 }
[2016-01-23 16:13:33.727] [DEBUG] CognitoHelper - getOpenIdTokenForDeveloperIdentity { IdentityPoolId: 'ap-northeast-1:84e40d07-e851-**_**********_',
  Logins: { '**_********.com': 'user@test.com' } }
    1) "before all" hook: create test user if does not exist

  0 passing (3s)
  1 failing

  1) CognitoHelper. "before all" hook: create test user if does not exist:
     Uncaught AssertionError: 'UnrecognizedClientException' == 409
      at test/cognito-helper.js:20:16
      at Response.<anonymous> (cognito-helper.js:383:13)
      at Request.<anonymous> (node_modules/aws-sdk/lib/request.js:354:18)
      at Request.callListeners (node_modules/aws-sdk/lib/sequential_executor.js:105:20)
      at Request.emit (node_modules/aws-sdk/lib/sequential_executor.js:77:10)
      at Request.emit (node_modules/aws-sdk/lib/request.js:596:14)
      at Request.transition (node_modules/aws-sdk/lib/request.js:21:10)
      at AcceptorStateMachine.runTo (node_modules/aws-sdk/lib/state_machine.js:14:12)
      at node_modules/aws-sdk/lib/state_machine.js:26:10
      at Request.<anonymous> (node_modules/aws-sdk/lib/request.js:37:9)
      at Request.<anonymous> (node_modules/aws-sdk/lib/request.js:598:12)
      at Request.callListeners (node_modules/aws-sdk/lib/sequential_executor.js:115:18)
      at Request.emit (node_modules/aws-sdk/lib/sequential_executor.js:77:10)
      at Request.emit (node_modules/aws-sdk/lib/request.js:596:14)
      at Request.transition (node_modules/aws-sdk/lib/request.js:21:10)
      at AcceptorStateMachine.runTo (node_modules/aws-sdk/lib/state_machine.js:14:12)
      at node_modules/aws-sdk/lib/state_machine.js:26:10
      at Request.<anonymous> (node_modules/aws-sdk/lib/request.js:37:9)
      at Request.<anonymous> (node_modules/aws-sdk/lib/request.js:598:12)
      at Request.callListeners (node_modules/aws-sdk/lib/sequential_executor.js:115:18)
      at callNextListener (node_modules/aws-sdk/lib/sequential_executor.js:95:12)
      at Request.RESET_RETRY_STATE (node_modules/aws-sdk/lib/event_listeners.js:378:9)
      at Request.callListeners (node_modules/aws-sdk/lib/sequential_executor.js:101:18)
      at Request.emit (node_modules/aws-sdk/lib/sequential_executor.js:77:10)
      at Request.emit (node_modules/aws-sdk/lib/request.js:596:14)
      at Request.transition (node_modules/aws-sdk/lib/request.js:21:10)
      at AcceptorStateMachine.runTo (node_modules/aws-sdk/lib/state_machine.js:14:12)
      at node_modules/aws-sdk/lib/state_machine.js:26:10
      at Request.<anonymous> (node_modules/aws-sdk/lib/request.js:37:9)
      at Request.<anonymous> (node_modules/aws-sdk/lib/request.js:598:12)
      at Request.callListeners (node_modules/aws-sdk/lib/sequential_executor.js:115:18)
      at Request.emit (node_modules/aws-sdk/lib/sequential_executor.js:77:10)
      at Request.emit (node_modules/aws-sdk/lib/request.js:596:14)
      at Request.transition (node_modules/aws-sdk/lib/request.js:21:10)
      at AcceptorStateMachine.runTo (node_modules/aws-sdk/lib/state_machine.js:14:12)
      at node_modules/aws-sdk/lib/state_machine.js:26:10
      at Request.<anonymous> (node_modules/aws-sdk/lib/request.js:37:9)
      at Request.<anonymous> (node_modules/aws-sdk/lib/request.js:598:12)
      at Request.callListeners (node_modules/aws-sdk/lib/sequential_executor.js:115:18)
      at Request.emit (node_modules/aws-sdk/lib/sequential_executor.js:77:10)
      at Request.emit (node_modules/aws-sdk/lib/request.js:596:14)
      at Request.transition (node_modules/aws-sdk/lib/request.js:21:10)
      at AcceptorStateMachine.runTo (node_modules/aws-sdk/lib/state_machine.js:14:12)
      at node_modules/aws-sdk/lib/state_machine.js:26:10
      at Request.<anonymous> (node_modules/aws-sdk/lib/request.js:37:9)
      at Request.<anonymous> (node_modules/aws-sdk/lib/request.js:598:12)
      at Request.callListeners (node_modules/aws-sdk/lib/sequential_executor.js:115:18)
      at Request.emit (node_modules/aws-sdk/lib/sequential_executor.js:77:10)
      at Request.emit (node_modules/aws-sdk/lib/request.js:596:14)
      at Request.transition (node_modules/aws-sdk/lib/request.js:21:10)
      at AcceptorStateMachine.runTo (node_modules/aws-sdk/lib/state_machine.js:14:12)
      at node_modules/aws-sdk/lib/state_machine.js:26:10
      at Request.<anonymous> (node_modules/aws-sdk/lib/request.js:37:9)
      at Request.<anonymous> (node_modules/aws-sdk/lib/request.js:598:12)
      at Request.callListeners (node_modules/aws-sdk/lib/sequential_executor.js:115:18)
      at callNextListener (node_modules/aws-sdk/lib/sequential_executor.js:95:12)
      at IncomingMessage.onEnd (node_modules/aws-sdk/lib/event_listeners.js:209:11)
      at endReadableNT (_stream_readable.js:905:12)

**Comment by vanerleo** [comment]
i've set COGNITO_DEVELOPER_PROVIDER_NAME in the .env

getting this : 

[2016-01-23 20:17:22.199] [DEBUG] CognitoHelper - getOpenIdTokenForDeveloperIdentity { IdentityPoolId: 'ap-northeast-1:84e40d07-e851-******',
  Logins: { 'myprovidername': 'user@test.com' } }
    1) "before all" hook: create test user if does not exist
1) CognitoHelper. "before all" hook: create test user if does not exist:
     Uncaught AssertionError: 'UnrecognizedClientException' == 409
      at test/cognito-helper.js:20:16
      at Response.<anonymous> (cognito-helper.js:383:13)
      at Request.<anonymous> (node_modules/aws-sdk/lib/request.js:354:18)

**Comment by olegabu** [comment]
let me take a look

**Comment by vanerleo** [comment]
are you able to confirm?

**Comment by olegabu** [comment]
Not yet. Will get to it tomorrow morning. Thanks for your patience.

**Comment by vanerleo** [comment]
any news on this?

**Comment by Jorriss** [comment]
@vanerleo I ran into the same problem have you configured the COGNITO_DEVELOPER_PROVIDER_NAME? I populated the COGNITO_DEVELOPER_PROVIDER_NAME with the same value that was in Identity pool > Authentication provider > Custom.

**Comment by vsantosu** [comment]
Any news on this? I'm having the same problem, and I set COGNITO_DEVELOPER_PROVIDER_NAME to Authentication provider  Custom.

**Comment by steveww** [comment]
I have just tried to follow the install process and set up everything as per the guide. Yep getting the same error.

As there has not been any activity on this repository for some time I am guessing it is not longer maintained?

**Comment by vsantosu** [comment]
Ok, so I solve this problem,

Digging more into the stack trace, I add a console.out of the error and it turns out the cause of the problem is that the AWS driver cannot find the region, so when you do the request it shows this:

`1) "before all" hook: create test user if does not exist`

But the real error is this:

`{ ResourceNotFoundException: IdentityPool 'us-west-2:5....' not found.`

To fix this, just open **cognito-helper.js** and add the following line:

`
AWS.config.update({region: 'us-west-2'});
`

Note that this is my region, you need to change this to yours. I added this line just after line 30(if else block).

It would be great if a hero put this in the config.js as AWS_REGION and it is pass automatically. Hope it helps. I'm a bit short of time to pull requests now.
